### ISSUE TITLE
Issue when changing default locale

### ISSUE THREAD

**Issue by eyeonx** [statamic/v2-hub#1110]
### Expected behaviour
It should be possible to change the default locale to german or french without breaking the control panel functionality.

### Actual behaviour
Changing the default locale to others languages than english cause a `ERR_TOO_MANY_REDIRECTS` error.

### Server configuration
**Operating system**: Mac OS

**Web server:** Linux

**PHP version:** 7.0

**Statamic version:** 2.1.17

**Updated from an older Statamic or fresh install:** Updated

**List of installed addons:** null

**Comment by jasonvarga** [comment]
Did you also change the locale in index.php?

**Comment by peimn** [comment]
Also changing default locale causes 404 errors on assets. #1038

**Comment by eyeonx** [comment]
@jasonvarga I changed it also in index.php (this part is not documented), I searched for the right locale but I don't know where it needs to be extracted. I tried to save the file into the `site/lang/` folder but the control panel is still not translated.

**Comment by jasonvarga** [comment]
Did you go through https://docs.statamic.com/localization ?

**Comment by eyeonx** [comment]
@jasonvarga sure, and I see nothing about localising the control panel. Changing the default language to German (de, de_DE) on system settings and index.php files leave the installation without a translation for the control panel. I found this repository https://github.com/statamic/i18n with a list of localisations but I don't know where to put those files.

**Comment by jasonvarga** [comment]
I just added some docs on translating the control panel.

**Comment by eyeonx** [comment]
Thanks @jasonvarga, really helpful! I am close to mark the issue as solved, I have only another question first:

Is that bad, when I set German as the primary language on the control panel and delete English, then click on save, the English language settings are re-added from the system into the language list?

Here a screenshot:
![Screenshot illustrating the unexpected behavior](https://cloud.githubusercontent.com/assets/17007410/20395218/6f30a980-ace2-11e6-8af2-34d395545625.png)

**Comment by jasonvarga** [comment]
Ah yes that would be a bug. Nice find. I will open a separate issue for this.

However, the only downside to this is that English will show in the locale selector when editing content. You can just ignore it for now.

**Comment by eyeonx** [comment]
Ok, perfect! Thank you very much for the fast response time.
Statamic it's really great... well done guys!

**Comment by ebeauchamps** [comment]
I am absolutly certain you don't have to change the default locale in index.php.
I have had numerous conversations with @jackmcdade about that and that's why it is not documented. 

But as of 2.1.17 and below, you must declare the locale in both settings.yaml and the user file: if you don't do it, the CP won't be 100% translated. So, as of 2.1.17, you cannot have a CP in English for some users and in French for others, but this behavior is going to be corrected in a future release.

**Comment by eyeonx** [comment]
@ebeauchamps it doesn't work your way... I still get an `ERR_TOO_MANY_REDIRECTS`error.

**Comment by ebeauchamps** [comment]
Interesting exchange....

My default locale is `en` in index.php, locales are `en` and `fr` (in that order) in settings.yaml, locale is `fr` in cp.yaml and locale is `fr` in my user own yaml file. The user get a 100% translated CP.

If I don't declare `fr` in cp.yaml, the CP is 90% translated but this small glitch is going to be corrected in a future release.

I should precise that my default site is for English (statamic.dev/) and French is located at statamic.dev/fr/
Indeed, when I put `fr` in index.php and then tried to access the cp, the url statamic.dev/cp was always redirecting to statamic.dev/fr/cp which obviously did not work.

**Comment by jasonvarga** [comment]
Your index.php needs to contain the default locale, or you will get a redirect problem.

**Comment by ebeauchamps** [comment]
Can now the default locale (the first one) be different from `en` ?

**Comment by jasonvarga** [comment]
Yes

**Comment by ebeauchamps** [comment]
OK, I should try another setup though. Thanks Jason.

**Comment by eyeonx** [comment]
@ebeauchamps in my case, I have German as default locale and I'm not using English at all... that configuration cause an `ERR_TOO_MANY_REDIRECTS` error when you try to login in the Control Panel, if you forget to update the default locale in index.php.
