### ISSUE TITLE
get_content does not display localized results

### ISSUE THREAD

**Issue by zenboy4ever** [statamic/v2-hub#989]
### Expected behaviour

{{ get_content from="{ segment_1 }" }}{{ title }}... should display localized value
### Actual behaviour

The English value is displayed
### Steps to reproduce

{{ get_content from="{ segment_1 }" }}{{ title }}...
### Server configuration

**Operating system**:

**Web server:**
Ubuntu
**PHP version:**
7.0
**Statamic version:**
2.1.9
**Updated from an older Statamic or fresh install:**
Updated

Note:
get_content does work correctly if the values are in an array and retrieved using a tag pair

**Comment by rrelmy** [comment]
`{{ parent }}` is also affected

The problem is down deep inside the `ContentService` class, the `uri` and `uriExists` both use the default locale.

Both methods should probably use the current locale and accept an optional parameter `$locale` to overwrite it.

**Comment by jackmcdade** [comment]
I _believe_ this is fixed, can you guys confirm?

**Comment by rrelmy** [comment]
Can we reopen this?

`ContentService` always use `default_locale()` as example in `uriExists`.
This leads to problems when the slug is different in the secondary locale.

The code in the original issue still breaks
```
{{ get_content from="{ segment_1 }" }}
    {{ title }}
{{ /get_content }}
```
